services:
  identityprovider:
    image: nono/idp:latest
    build:
      context: .
      dockerfile: Idp.Api/Dockerfile
    ports:    
      - "5082:80"
      - "7254:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - database
    networks:
      - backend-network
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Guilherme123@
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - backend-network
    
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"            
      - "4510-4559:4510-4559"  
      - "443:443"              
    environment:
      - SERVICES=kms,s3
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_SECRET}
      - DEBUG=${DEBUG:-0}
#      - AWS_ACCESS_KEY_ID=test
#      - AWS_SECRET_ACCESS_KEY=test
#      - LOCALSTACK_CLOUD_API=1
#      - LOCALSTACK_HOST=localhost.localstack.cloud
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend-network

volumes:
  sqlserver-data:
    
networks:
  backend-network:
    driver: bridge